#COLAB 설정

google drive mount  
google drive를 colab환경에 mount해서 colab에서 파일을 읽고 쓸수 있도록 설정  

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import os
print(os.getcwd())
print(os.listdir())
print(os.listdir(os.path.join("drive","MyDrive")))

/content
['.config', 'drive', 'sample_data']
['xlnet_classificatin', '.ipynb_checkpoints', 'Colab Notebooks', 'DL_term', 'TF_IDF_SentimentAnalysis', 'AI_SA_hw_answer', 'AI_SA_hw', '랩세미나(new)', '논문', '79_김균엽(가천대학교).mp4', 'vjn-oiep-zee - 2021년 7월 12일.gjam', 'baseline_val.json', 'result.json', 'result2.json', '제목 없는 문서.gdoc', '종합시험_2022_김균엽.docx', 'tmp', '랩세미나', '자연어처리 오픈 튜토리얼 신청서 2022-1.gform', '소서리스 DPS 시뮬레이터 (by 치즈메기)의 사본.gsheet', '・ヘ・?의 사본.gsheet', '제목 없는 설문지.gform', '자연어처리 오픈 튜토리얼 신청서 2022-1(응답).gsheet']


# NUMPY 실습

In [ ]:
import numpy as np
import pandas as pd
import torch

Ndarray  
numpy.array()함수에 list like형태의 데이터를 입력하여 생성한다.  
doc: https://compmath.korea.ac.kr/appmath/NumpyBasics.html  

In [ ]:
data = [1,2,3]
print(type(data))

numpy_data = np.array(data)
print(numpy_data)
print(type(numpy_data))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


Ndarray는 행렬 형태의 데이터   
행렬은 각 행과 열에 데이터의 크기가 같아야한다.

python의 list는 단순 데이터의 묶음 형태이기 때문에 [[1,2],1,(1,2,3)] 같이 각 element의 형태, 크기, 타입이 자유로움   
numpy의 ndarray는 행렬, 텐서와 같은형태를 가지기 때문에 각 elements의 타입이 동일해야하며 모든 열과 행의 크기가 같아야 함

In [ ]:
python_list = [[1,2],1,(1.0,2,3),"string"]
print(python_list)

#ndarray는 모든 행과 열의 크기가 같아야하기에 정상적인 데이터가 생성되지 않음
a = [[1,2],[1,2,3]]
np_a = np.array(a)
print("\n")
print(np_a)
print(np_a.shape)

#2차원 list를 이용한 ndarray 생성
b = [[1,2,3],[4,5,6]]
np_b = np.array(b)
print("\n")
print(np_b)
print(np_b.shape)


[[1, 2], 1, (1.0, 2, 3), 'string']


[list([1, 2]) list([1, 2, 3])]
(2,)


[[1 2 3]
 [4 5 6]]
(2, 3)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


ndarray는 상수와의 연산, ndarray와의 연산, 행렬연산 등 다양한 연산을 지원한다.

In [ ]:
b = [[1,2,3],[4,5,6]]
np_b = np.array(b)

c = [[6,5,4],[3,2,1]]
np_c = np.array(c)

print("tensor b")
print(np_b)
print(np_b.shape)

print("\ntensor c")
print(np_c)
print(np_c.shape)

print("\ntranspose c")
print(np.transpose(np_c))
print(np_c.T)

print("\n flatten c")
print(np_c.flatten())

print("\nreshape c")
print(np_c.reshape((3,2)))
print(np_c.shape)

print("\nb*2:")
print(np_b*2)

#element wise add element단위 덧셈
print("\nb+c:")
print(np_b+np_c)

#element wise product element단위 곱셈
print("\nb*c:")
print(np_b*np_c)

#dot 행렬곱
print("\nb dot transpose c")
print(np.dot(np_b,np_c.T))

tensor b
[[1 2 3]
 [4 5 6]]
(2, 3)

tensor c
[[6 5 4]
 [3 2 1]]
(2, 3)

transpose c
[[6 3]
 [5 2]
 [4 1]]
[[6 3]
 [5 2]
 [4 1]]

 flatten c
[6 5 4 3 2 1]

reshape c
[[6 5]
 [4 3]
 [2 1]]
(2, 3)

b*2:
[[ 2  4  6]
 [ 8 10 12]]

b+c:
[[7 7 7]
 [7 7 7]]

b*c:
[[ 6 10 12]
 [12 10  6]]

b dot transpose c
[[28 10]
 [73 28]]
